name: fastcut
description: FastCut beta — mobile quick video editor
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # видео
  video_player: ^2.8.1

  # НОВЫЙ file_picker (под v2 embedding)
  file_picker: ^8.0.0

  # разрешения
  permission_handler: ^11.3.0

  # путь для временного экспорта
  path_provider: ^2.1.2

  # id для клипов
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
